CREATE TABLE IF NOT EXISTS employee_policy_tagging (
  id INT AUTO_INCREMENT PRIMARY KEY,
  emp_code VARCHAR(50) NOT NULL,
  emp_id VARCHAR(50) NULL,
  emp_name VARCHAR(100) NULL,
  category VARCHAR(100) NULL,
  company VARCHAR(100) NULL,
  location VARCHAR(100) NULL,
  division VARCHAR(100) NULL,
  department VARCHAR(100) NULL,
  section VARCHAR(100) NULL,
  subsection VARCHAR(100) NULL,
  designation VARCHAR(100) NULL,
  
  -- Policy Fields
  overtime_policy_rule VARCHAR(50) NULL,
  overtime_policy_date DATE NULL,
  holiday_incentive_rule VARCHAR(50) NULL,
  holiday_incentive_date DATE NULL,
  duty_roster_policy_rule VARCHAR(50) NULL,
  duty_roster_policy_date DATE NULL,
  leave_policy_rule VARCHAR(50) NULL,
  leave_policy_date DATE NULL,
  maternity_leave_policy_rule VARCHAR(50) NULL,
  maternity_leave_policy_date DATE NULL,
  attendance_bonus_policy_rule VARCHAR(50) NULL,
  attendance_bonus_policy_date DATE NULL,
  absent_deduction_policy_rule VARCHAR(50) NULL,
  absent_deduction_policy_date DATE NULL,
  late_deduction_policy_rule VARCHAR(50) NULL,
  late_deduction_policy_date DATE NULL,
  bonus_policy_rule VARCHAR(50) NULL,
  bonus_policy_date DATE NULL,
  tax_policy_rule VARCHAR(50) NULL,
  tax_policy_date DATE NULL,
  shift_policy_rule VARCHAR(50) NULL,
  shift_policy_date DATE NULL,
  tiffin_bill_policy_rule VARCHAR(50) NULL,
  tiffin_bill_policy_date DATE NULL,
  allowance_policy_rule VARCHAR(50) NULL,
  allowance_policy_date DATE NULL,
  early_out_deduction_policy_rule VARCHAR(50) NULL,
  early_out_deduction_policy_date DATE NULL,
  service_benefit_policy_rule VARCHAR(50) NULL,
  service_benefit_policy_date DATE NULL,
  hd_deduct_rule_rule VARCHAR(50) NULL,
  hd_deduct_rule_date DATE NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_emp_code (emp_code),
  UNIQUE KEY unique_emp_code (emp_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
