CREATE TABLE IF NOT EXISTS employee_education (
  id INT AUTO_INCREMENT PRIMARY KEY,
  emp_code VARCHAR(50) NOT NULL,
  emp_id VARCHAR(50) NULL,
  emp_name VARCHAR(100) NULL,
  category VARCHAR(100) NULL,
  company VARCHAR(100) NULL,
  location VARCHAR(100) NULL,
  division VARCHAR(100) NULL,
  department VARCHAR(100) NULL,
  section VARCHAR(100) NULL,
  subsection VARCHAR(100) NULL,
  designation VARCHAR(100) NULL,
  course_name VARCHAR(100) NULL,
  board VARCHAR(100) NULL,
  institution VARCHAR(200) NULL,
  discipline VARCHAR(100) NULL,
  major_subject VARCHAR(100) NULL,
  year VARCHAR(10) NULL,
  result VARCHAR(50) NULL,
  education_nature VARCHAR(50) DEFAULT 'Academic',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_emp_code (emp_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;